'use strict';

const { validateProgramSecurity } = require('./security-validator');
const { createProgramIR, hashIR } = require('./ir');
const path = require('path');

function escapeJsString(value) {
  return JSON.stringify(String(value || ''));
}

function compileToWasmModuleSkeleton(ast, options = {}) {
  validateProgramSecurity(ast, { mode: String(options.securityMode || 'strict').toLowerCase() });
  const ir = createProgramIR(ast, { sourceLabel: options.sourceLabel || '' });
  const irHash = hashIR(ir);
  const preset = Array.isArray(ast?.presets) && ast.presets[0] ? ast.presets[0] : null;
  const presetName = String(preset?.name || '');
  const sourceLabel = String(options.sourceLabel || '');
  const defaultFallbackModulePath = sourceLabel
    ? `./${path.basename(sourceLabel)}.generated.js`
    : './preset.generated.js';

  return [
    "'use strict';",
    '',
    '// Generated by dali-lang compiler (WASM hybrid target).',
    '// Runtime order: try WASM init -> fallback to JS WebAudio generated module.',
    `const __daliIR = ${JSON.stringify(ir, null, 2)};`,
    `const __DEFAULT_FALLBACK_MODULE = ${escapeJsString(defaultFallbackModulePath)};`,
    '',
    'function __tryRequire(modPath, requireFn) {',
    '  const req = typeof requireFn === "function" ? requireFn : (typeof require === "function" ? require : null);',
    '  if (!req) return null;',
    '  try {',
    '    return req(modPath);',
    '  } catch (_) {',
    '    return null;',
    '  }',
    '}',
    '',
    'async function __loadWasmBytes(opts) {',
    '  if (!opts || typeof opts !== "object") return null;',
    '  if (opts.wasmBytes && (opts.wasmBytes instanceof Uint8Array || opts.wasmBytes instanceof ArrayBuffer)) {',
    '    return opts.wasmBytes instanceof Uint8Array ? opts.wasmBytes : new Uint8Array(opts.wasmBytes);',
    '  }',
    '  if (typeof opts.fetchWasm === "function") {',
    '    const fetched = await opts.fetchWasm();',
    '    if (fetched instanceof Uint8Array) return fetched;',
    '    if (fetched instanceof ArrayBuffer) return new Uint8Array(fetched);',
    '  }',
    '  return null;',
    '}',
    '',
    'async function initWasmRuntime(opts = {}) {',
    "  const status = { ok: false, mode: 'none', reason: '', wasm: { linked: false }, fallback: { loaded: false, modulePath: '' } };",
    '  const preferWasm = opts.preferWasm !== false;',
    '  const allowFallback = opts.allowFallback !== false;',
    '',
    '  if (preferWasm) {',
    '    if (typeof WebAssembly === "undefined") {',
    "      status.reason = 'WebAssembly not available';",
    '    } else {',
    '      try {',
    '        const wasmBytes = await __loadWasmBytes(opts);',
    '        if (wasmBytes && wasmBytes.byteLength > 0) {',
    '          const result = await WebAssembly.instantiate(wasmBytes, opts.importObject || {});',
    '          status.ok = true;',
    "          status.mode = 'wasm';",
    '          status.wasm.linked = true;',
    '          status.wasm.byteLength = wasmBytes.byteLength;',
    '          return {',
    '            status,',
    '            mode: status.mode,',
    '            wasmInstance: result && (result.instance || result),',
    '            exports: result && result.instance && result.instance.exports ? result.instance.exports : (result && result.exports ? result.exports : {}),',
    '            // Graph hook is intentionally null until DSP kernels are mapped to WebAudio/Worklet pipeline.',
    '            buildGraph: null',
    '          };',
    '        }',
    "        status.reason = 'No WASM bytes provided';",
    '      } catch (err) {',
    "        status.reason = err && err.message ? err.message : 'WASM init failed';",
    '      }',
    '    }',
    '  } else {',
    "    status.reason = 'WASM preference disabled';",
    '  }',
    '',
    '  if (allowFallback) {',
    '    const fallbackModulePath = String(opts.fallbackModulePath || __DEFAULT_FALLBACK_MODULE);',
    '    const mod = __tryRequire(fallbackModulePath, opts.requireFn);',
    '    if (mod && typeof mod.buildGraph === "function") {',
    '      status.ok = true;',
    "      status.mode = 'js-fallback';",
    '      status.fallback.loaded = true;',
    '      status.fallback.modulePath = fallbackModulePath;',
    '      return {',
    '        status,',
    '        mode: status.mode,',
    '        buildGraph: mod.buildGraph,',
    '        buildGraphSafe: typeof mod.buildGraphSafe === "function" ? mod.buildGraphSafe : null,',
    '        module: mod',
    '      };',
    '    }',
    '  }',
    '',
    "  throw new Error(`[DALI WASM] init failed: ${status.reason || 'unknown'} (fallback unavailable)`);",
    '}',
    '',
    'module.exports = {',
    `  presetName: ${JSON.stringify(presetName)},`,
    "  target: 'wasm-hybrid',",
    `  sourceLabel: ${escapeJsString(sourceLabel)},`,
    '  defaultFallbackModulePath: __DEFAULT_FALLBACK_MODULE,',
    `  irHash: ${JSON.stringify(irHash)},`,
    '  ir: __daliIR,',
    '  initWasmRuntime',
    '};',
    ''
  ].join('\n');
}

module.exports = {
  compileToWasmModuleSkeleton
};
