'use strict';

const { validateProgramSecurity } = require('./security-validator');
const { createProgramIR, hashIR } = require('./ir');
const path = require('path');

function compileToNativeSkeleton(ast, options = {}) {
  validateProgramSecurity(ast, { mode: String(options.securityMode || 'strict').toLowerCase() });
  const ir = createProgramIR(ast, {
    sourceLabel: options.sourceLabel || '',
    securityMode: options.securityMode || 'strict',
    targetClass: 'native-poc',
    includeTimestamp: false
  });
  const irHash = hashIR(ir);
  const preset = Array.isArray(ast?.presets) && ast.presets[0] ? ast.presets[0] : null;
  const presetName = String(preset?.name || '');

  // POC: Generate simple C code for bass enhancer
  const cCode = generateBassEnhancerC(ir);

  return `#include <stdio.h>
#include <stdlib.h>
#include <math.h>

// Generated by dali-lang compiler (Native POC target)
// IR Hash: ${irHash}
// Preset: ${presetName}

${cCode}

int main() {
  printf("Native POC: Bass Enhancer\\n");
  return 0;
}`;
}

function generateBassEnhancerC(ir) {
  // Real implementation with parameters, reverb, and SIMD POC
  return [
    '// Biquad filter struct',
    'typedef struct {',
    '  double b0, b1, b2, a1, a2;',
    '  double x1, x2, y1, y2;',
    '} Biquad;',
    '',
    'void biquad_init(Biquad *bq, double b0, double b1, double b2, double a0, double a1, double a2) {',
    '  bq->b0 = b0 / a0;',
    '  bq->b1 = b1 / a0;',
    '  bq->b2 = b2 / a0;',
    '  bq->a1 = a1 / a0;',
    '  bq->a2 = a2 / a0;',
    '  bq->x1 = bq->x2 = bq->y1 = bq->y2 = 0.0;',
    '}',
    '',
    'double biquad_process(Biquad *bq, double input) {',
    '  double output = bq->b0 * input + bq->b1 * bq->x1 + bq->b2 * bq->x2 - bq->a1 * bq->y1 - bq->a2 * bq->y2;',
    '  bq->x2 = bq->x1;',
    '  bq->x1 = input;',
    '  bq->y2 = bq->y1;',
    '  bq->y1 = output;',
    '  return output;',
    '}',
    '',
    '// Compressor struct',
    'typedef struct {',
    '  double threshold, ratio, attack, release, makeup;',
    '  double envelope;',
    '  double sample_rate;',
    '} Compressor;',
    '',
    'void compressor_init(Compressor *comp, double threshold, double ratio, double attack, double release, double makeup, double sample_rate) {',
    '  comp->threshold = threshold;',
    '  comp->ratio = ratio;',
    '  comp->attack = attack / 1000.0; // ms to s',
    '  comp->release = release / 1000.0;',
    '  comp->makeup = makeup;',
    '  comp->envelope = 0.0;',
    '  comp->sample_rate = sample_rate;',
    '}',
    '',
    'double compressor_process(Compressor *comp, double input) {',
    '  double abs_input = fabs(input);',
    '  double coeff = (abs_input > comp->envelope) ? comp->attack : comp->release;',
    '  comp->envelope = comp->envelope * (1.0 - coeff) + abs_input * coeff;',
    '  double gain = (comp->envelope > comp->threshold) ? pow(comp->envelope / comp->threshold, comp->ratio - 1.0) : 1.0;',
    '  return input * gain * pow(10.0, comp->makeup / 20.0);',
    '}',
    '',
    '// Limiter struct',
    'typedef struct {',
    '  double ceiling;',
    '} Limiter;',
    '',
    'void limiter_init(Limiter *lim, double ceiling) {',
    '  lim->ceiling = ceiling;',
    '}',
    '',
    'double limiter_process(Limiter *lim, double input) {',
    '  double max_val = pow(10.0, lim->ceiling / 20.0);',
    '  if (input > max_val) return max_val;',
    '  if (input < -max_val) return -max_val;',
    '  return input;',
    '}',
    '',
    '// Bass Enhancer struct',
    'typedef struct {',
    '  double preamp_gain;',
    '  Biquad low_shelf;',
    '  Biquad peaking1;',
    '  Biquad peaking2;',
    '  Compressor compressor;',
    '  Limiter limiter;',
    '} BassEnhancer;',
    '',
    'void init_bass_enhancer(BassEnhancer *be, double sample_rate) {',
    '  be->preamp_gain = pow(10.0, -4.5 / 20.0); // -4.5dB',
    '  // Low shelf: freq=58Hz, gain=9.0dB, q=0.72',
    '  double A = pow(10.0, 9.0 / 40.0);',
    '  double omega = 2.0 * M_PI * 58.0 / sample_rate;',
    '  double alpha = sin(omega) / (2.0 * 0.72);',
    '  double cos_omega = cos(omega);',
    '  double b0 = A * ((A + 1) + (A - 1) * cos_omega + 2 * sqrt(A) * alpha);',
    '  double b1 = -2 * A * ((A - 1) + (A + 1) * cos_omega);',
    '  double b2 = A * ((A + 1) + (A - 1) * cos_omega - 2 * sqrt(A) * alpha);',
    '  double a0 = (A + 1) - (A - 1) * cos_omega + 2 * sqrt(A) * alpha;',
    '  double a1 = 2 * ((A - 1) - (A + 1) * cos_omega);',
    '  double a2 = (A + 1) - (A - 1) * cos_omega - 2 * sqrt(A) * alpha;',
    '  biquad_init(&be->low_shelf, b0, b1, b2, a0, a1, a2);',
    '  // Peaking1: freq=86Hz, gain=5.0dB, q=0.95',
    '  A = pow(10.0, 5.0 / 40.0);',
    '  omega = 2.0 * M_PI * 86.0 / sample_rate;',
    '  alpha = sin(omega) / (2.0 * 0.95);',
    '  cos_omega = cos(omega);',
    '  b0 = 1 + alpha * A;',
    '  b1 = -2 * cos_omega;',
    '  b2 = 1 - alpha * A;',
    '  a0 = 1 + alpha / A;',
    '  a1 = -2 * cos_omega;',
    '  a2 = 1 - alpha / A;',
    '  biquad_init(&be->peaking1, b0, b1, b2, a0, a1, a2);',
    '  // Peaking2: freq=145Hz, gain=2.2dB, q=1.05',
    '  A = pow(10.0, 2.2 / 40.0);',
    '  omega = 2.0 * M_PI * 145.0 / sample_rate;',
    '  alpha = sin(omega) / (2.0 * 1.05);',
    '  cos_omega = cos(omega);',
    '  b0 = 1 + alpha * A;',
    '  b1 = -2 * cos_omega;',
    '  b2 = 1 - alpha * A;',
    '  a0 = 1 + alpha / A;',
    '  a1 = -2 * cos_omega;',
    '  a2 = 1 - alpha / A;',
    '  biquad_init(&be->peaking2, b0, b1, b2, a0, a1, a2);',
    '  // Compressor: threshold=-22dB, ratio=3.2, attack=12ms, release=220ms, makeup=1.4dB',
    '  compressor_init(&be->compressor, pow(10.0, -22.0 / 20.0), 3.2, 12.0, 220.0, 1.4, sample_rate);',
    '  // Limiter: ceiling=-1.2dB',
    '  limiter_init(&be->limiter, -1.2);',
    '}',
    '',
    'void set_param_bass_enhancer(BassEnhancer *be, int param_id, double value) {',
    '  // POC: no params yet',
    '}',
    '',
    'double process_sample_bass_enhancer(BassEnhancer *be, double input) {',
    '  double out = input * be->preamp_gain;',
    '  out = biquad_process(&be->low_shelf, out);',
    '  out = biquad_process(&be->peaking1, out);',
    '  out = biquad_process(&be->peaking2, out);',
    '  out = compressor_process(&be->compressor, out);',
    '  out = limiter_process(&be->limiter, out);',
    '  return out;',
    '}',
    '',
    'void process_block_bass_enhancer(BassEnhancer *be, double *input, double *output, int num_samples) {',
    '  for (int i = 0; i < num_samples; i++) {',
    '    output[i] = process_sample_bass_enhancer(be, input[i]);',
    '  }',
    '}'
  ].join('\\n');
}

module.exports = { compileToNativeSkeleton };